### ISSUE TITLE
Code missing? if this is the official repo for the book then why is the code missing?

### ISSUE THREAD

**Issue by necronomican** [falloutdurham/beginners-pytorch-deep-learning#1]

**Comment by faisito** [comment]
true dat!
@ian, where's the code man? your book is very promising, but you can't have a hands-on book without code. not cool.

**Comment by necronomican** [comment]
> true dat!
> @ian, where's the code man? your book is very promising, but you can't have a hands-on book without code. not cool.

Yes. I have to clean up data as some files needed for chapter 2 are corrupted. I don't mind but this is demotivating. I am also facing errors, though I have typed in every line word to word. 
@falloutdurham when will you upload the code? Is there an alternate source?

**Comment by falloutdurham** [comment]
Check the other repo for the downloading code - https://github.com/falloutdurham/pytorchupandrunning - I'm hoping to get most of the rest uploaded this week!

**Comment by necronomican** [comment]
> Check the other repo for the downloading code - https://github.com/falloutdurham/pytorchupandrunning - I'm hoping to get most of the rest uploaded this week!

Ah! Only if you would have replied a moment ago, wouldn't have typed in the above comment.

**Comment by falloutdurham** [comment]
np ;)

**Comment by falloutdurham** [comment]
(and apologies - I've been a little ill and running behind on this part!)

**Comment by winkhai** [comment]
@falloutdurham oh that sucks! Hope you're feeling better.  really enjoyed your content as well. I've the online version and looks like your book was just released very recently. 
so the link you posted above isn't pertinent to training the model using pytorch, unless I missing something?

**Comment by falloutdurham** [comment]
Thank you! I'm still a little behind but I'm still hoping to get at least notebooks for Chapters 2 -6 up this weekend! The link I posted earlier is for downloading the cat/fish dataset (and the book got renamed partway along the process, hence the slight confusion in repos). The model training should be up by the end of Sunday! And again, apologies to all…

**Comment by necronomican** [comment]
> Thank you! I'm still a little behind but I'm still hoping to get at least notebooks for Chapters 2 -6 up this weekend! The link I posted earlier is for downloading the cat/fish dataset (and the book got renamed partway along the process, hence the slight confusion in repos). The model training should be up by the end of Sunday! And again, apologies to all…

That will be good. Get well soon!

**Comment by idudch** [comment]
hi, so the chapters 7+ notebooks will be posted one day as well?

**Comment by falloutdurham** [comment]
Yes! Chapter 7 is up already (as well as part of Chapter 9), and I'm hoping to fill in the gaps on 8 and 9 this week!
