### ISSUE TITLE
chapter 6

### ISSUE THREAD

**Issue by wubinbai** [falloutdurham/beginners-pytorch-deep-learning#12]
2 problems:
1 test not defined
2 shown below

device="cuda"
bs=64
PATH_TO_ESC50 = Path.cwd() / 'esc50'
test

train_esc50 = ESC50(PATH_TO_ESC50 / "train")
valid_esc50 = ESC50(PATH_TO_ESC50 / "valid")
test_esc50  = ESC50(PATH_TO_ESC50 / "test")

train_loader = torch.utils.data.DataLoader(train_esc50, batch_size = bs, shuffle = True)
valid_loader = torch.utils.data.DataLoader(valid_esc50, batch_size = bs, shuffle = True)
test_loader  = torch.utils.data.DataLoader(test_esc50, batch_size = bs, shuffle = True)

ValueErrorTraceback (most recent call last)
<ipython-input-5-acadcd621001> in <module>()
      8 test_esc50  = ESC50(PATH_TO_ESC50 / "test")
      9 
---> 10 train_loader = torch.utils.data.DataLoader(train_esc50, batch_size = bs, shuffle = True)
     11 valid_loader = torch.utils.data.DataLoader(valid_esc50, batch_size = bs, shuffle = True)
     12 test_loader  = torch.utils.data.DataLoader(test_esc50, batch_size = bs, shuffle = True)

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, num_workers, collate_fn, pin_memory, drop_last, timeout, worker_init_fn, multiprocessing_context)
    211             else:  # map-style
    212                 if shuffle:
--> 213                     sampler = RandomSampler(dataset)
    214                 else:
    215                     sampler = SequentialSampler(dataset)

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py in __init__(self, data_source, replacement, num_samples)
     92         if not isinstance(self.num_samples, int) or self.num_samples <= 0:
     93             raise ValueError("num_samples should be a positive integer "
---> 94                              "value, but got num_samples={}".format(self.num_samples))
     95 
     96     @property

ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by falloutdurham** [comment]
You'll need to download the ESC-50 dataset, unzip it, and point the notebook to the files.

https://github.com/karolpiczak/ESC-50#download

(I'll add it to the top of the notebook soon)
