### ISSUE TITLE
chapter 3

### ISSUE THREAD

**Issue by wubinbai** [falloutdurham/beginners-pytorch-deep-learning#13]
issue: no ./train directory

def check_image(path):
    try:
        im = Image.open(path)
        return True
    except:
        return False
img_transforms = transforms.Compose([
    transforms.Resize((64,64)),    
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                    std=[0.229, 0.224, 0.225] )
    ])
train_data_path = "./train/"
train_data = torchvision.datasets.ImageFolder(root=train_data_path,transform=img_transforms, is_valid_file=check_image)
val_data_path = "./val/"
val_data = torchvision.datasets.ImageFolder(root=val_data_path,transform=img_transforms, is_valid_file=check_image)
batch_size=64
train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size,shuffle=True)
val_data_loader  = torch.utils.data.DataLoader(val_data, batch_size=batch_size, shuffle=True)
if torch.cuda.is_available():
    device = torch.device("cuda") 
else:
    device = torch.device("cpu")

FileNotFoundErrorTraceback (most recent call last)
<ipython-input-5-f85b3dd69ef8> in <module>()
     12     ])
     13 train_data_path = "./train/"
---> 14 train_data = torchvision.datasets.ImageFolder(root=train_data_path,transform=img_transforms, is_valid_file=check_image)
     15 val_data_path = "./val/"
     16 val_data = torchvision.datasets.ImageFolder(root=val_data_path,transform=img_transforms, is_valid_file=check_image)

~/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py in __init__(self, root, transform, target_transform, loader, is_valid_file)
    207                                           transform=transform,
    208                                           target_transform=target_transform,
--> 209                                           is_valid_file=is_valid_file)
    210         self.imgs = self.samples

~/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py in __init__(self, root, loader, extensions, transform, target_transform, is_valid_file)
     91         super(DatasetFolder, self).__init__(root, transform=transform,
     92                                             target_transform=target_transform)
---> 93         classes, class_to_idx = self._find_classes(self.root)
     94         samples = make_dataset(self.root, class_to_idx, extensions, is_valid_file)
     95         if len(samples) == 0:

~/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py in _find_classes(self, dir)
    120         if sys.version_info >= (3, 5):
    121             # Faster and available in Python 3.5 and above
--> 122             classes = [d.name for d in os.scandir(dir) if d.is_dir()]
    123         else:
    124             classes = [d for d in os.listdir(dir) if os.path.isdir(os.path.join(dir, d))]

FileNotFoundError: [Errno 2] No such file or directory: './train/'

**Comment by falloutdurham** [comment]
I will have a look at this in more depth in the coming days, but my first thought is that you'll need to run the `download.py` script again either in that directory or alter the paths in the notebook to point to where they're living on your disk.

**Comment by wubinbai** [comment]
hi! I am a reader of your great book. However, I just can not find the Download.py as you described. Thanks!

**Comment by falloutdurham** [comment]
Apologies - I forgot to point out that it is in the Chapter 2 directory!

**Comment by wubinbai** [comment]
Hi, thank you for your answer! I tried to execute the python code downloads.py in chapter2 directory, however I got some error message, is it possible that you upload the data in the github or somewhere else?
thank you
Downloading 1393 images
Error downloading http://farm1.static.flickr.com/223/522289072_13b4f92d39.jpg
Error downloading http://farm1.static.flickr.com/28/100739452_5be2c11557.jpg
Error downloading http://farm1.static.flickr.com/1/1004527_527c0c32ce.jpg

**Comment by falloutdurham** [comment]
You may get some errors from the list of images depending if they're no longer available or not, but you should still end up with enough images downloaded for training. Just let the script run and then update the paths to the dataset appropriately.

**Comment by wubinbai** [comment]
Hi, thanks for you help. Besides errors, downloads.py seems to work. However, unfortunately, new errors has come when I implement Chapter3.ipynb in chapter3directory. The error shows:

Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
-------------------------------------------------
TypeError       Traceback (most recent call last)
~/git/programming_pytorch_for_dl/beginners-pytorch-deep-learning/chapter3/Chapter 3.py in <module>()
    124 train_data = torchvision.datasets.ImageFolder(root=train_data_path,transform=img_transforms, is_valid_file=check_image)
    125 val_data_path = "./val/"
--> 126 val_data = torchvision.datasets.ImageFolder(root=val_data_path,transform=img_transforms, is_valid_file=check_image)
    127 batch_size=64
    128 train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size,shuffle=True)

~/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py in __init__(self, root, transform, target_transform, loader, is_valid_file)
    207                                           transform=transform,
    208                                           target_transform=target_transform,
--> 209                                           is_valid_file=is_valid_file)
    210         self.imgs = self.samples

~/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py in __init__(self, root, loader, extensions, transform, target_transform, is_valid_file)
     95         if len(samples) == 0:
     96             raise (RuntimeError("Found 0 files in subfolders of: " + self.root + "\n"
---> 97                                 "Supported extensions are: " + ",".join(extensions)))
     98 
     99         self.loader = loader

TypeError: can only join an iterable

**Comment by falloutdurham** [comment]
It still looks like it's not finding the image files. I'll take a look this weekend for you - but my first instinct would be to make sure that ` val_data_path = "./val/"` value is actually pointing to where the files are stored on the disk, which may depend on where you're running `download.py`

**Comment by wubinbai** [comment]
HI, yes it looks like the problem of the val directory, and indeed, I check the val, it contains two folders, in which I find these two folders are blank itself.... So how may I fix this? previously, you mentioned that even if there is error running when I exe. download.py I could get image files or something and it is ok that I use Ctrl + C to terminate at some point. (Since is running like forever), so maybe that is a little problem downloading the data? How to fix this? Or is it possible to, say commit another code to solve this prob? thank you

**Comment by falloutdurham** [comment]
Hmm, I just ran the notebook myself locally, and I'm not seeing any issues with the training / validation. What are the names of those directories in that `val` directory? Providing you've got images in `val`, you can probably just delete them if they're blank…

**Comment by wubinbai** [comment]
HI, seriously, everything just doesn't work for me. Running the download.py:

Creating directory ./train/cat
Creating directory ./train/fish
Creating directory ./test/cat
Creating directory ./test/fish
Creating directory ./val/cat
Creating directory ./val/fish
Downloading 1393 images
Error downloading http://farm2.static.flickr.com/1245/1259825348_6a2aa94e8d.jpg
Error downloading http://farm2.static.flickr.com/1080/1029412358_7ee17550fc.jpg


I just have errors.

What is have is three dirs: train test and val
inside all of these I gott cat and fish directory, which are blank.

I copy the dir into chapter3, it just doesn't work.

**Comment by falloutdurham** [comment]
That is really odd. I'll zip up my local copy of the training/test/val directories and send it to you to try this week!

**Comment by falloutdurham** [comment]
Try this zip file! https://drive.google.com/open?id=16h8E7dnj5TpxF_ex4vF2do20iMWziM70

**Comment by picheny-nyu** [comment]
That zip file seems to also be missing many files.......

**Comment by haiyang1991Liu** [comment]
question? if I don't stop the script, the image will continue to download whether the unfound link exist?

**Comment by JzHuai0108** [comment]
Yes. Lots of images have 0 bytes or wrong sizes. What can I do?
![Screenshot from 2024-05-08 22-22-55](https://github.com/falloutdurham/beginners-pytorch-deep-learning/assets/8062561/ae5d986d-b6c7-46b0-8126-4b43e07b549f)
