### ISSUE TITLE
Chapter 2: "image file is truncated (XX bytes not processed)"

### ISSUE THREAD

**Issue by pavelanni** [falloutdurham/beginners-pytorch-deep-learning#17]
I've got this error when training the model from Chapter 2:
```
  File ".../Python/3.7.6/site-packages/PIL/ImageFile.py", line 220, in load
    raise IOError("image file is truncated (%d bytes not processed)" % len(b))
IOError: image file is truncated (57 bytes not processed)
```
I googled it and immediately found a solution here: https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images

So I added these lines before the training part and it helped.

```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES=True
```
Hopefully, it will help somebody else :-)  I can submit a PR, if necessary.

**Comment by falloutdurham** [comment]
Feel free to submit a PR! - Thanks! :)
