### ISSUE TITLE
Chapter 7 cam.ipynb casper.jpg/casper2.jpg missing

### ISSUE THREAD

**Issue by MarcusFra** [falloutdurham/beginners-pytorch-deep-learning#19]
Dear @falloutdurham,

would you mind to comment where to find casper.jpg. I copied your casper.jpg from the notebook to my drive and used that pic, but I had to adjust one line to make it work:

```
tensor = preprocess(image)
```
to
```
tensor = preprocess(image.convert('RGB'))
```

Maybe you can add the image to the directory and check whether the rgb conversion is necessary for the added one.

**Comment by falloutdurham** [comment]
https://github.com/falloutdurham/beginners-pytorch-deep-learning/commit/339e5327d7ddd7a819b0dad91f386df154320f05 

Should be there now!
