### ISSUE TITLE
Code for Class activation mapping

### ISSUE THREAD

**Issue by jhagege** [falloutdurham/beginners-pytorch-deep-learning#4]
Hi, I've been trying to follow the code examples from the class activation mapping workflow (chapter 7) but have a hard time understanding how this code fits with what comes before:

```
fts = sf[0].features[idx]
        prob = np.exp(to_np(log_prob))
        preds = np.argmax(prob[idx])
        fts_np = to_np(fts)
        f2=np.dot(np.rollaxis(fts_np,0,3), prob[idx])
        f2-=f2.min()
        f2/=f2.max()
        f2
plt.imshow(dx)
plt.imshow(scipy.misc.imresize(f2, dx.shape), alpha=0.5, cmap='jet');
```

Could you please post the code that is consistent with previous naming, or add a file in the repository to demonstrate this flow ? 

Thanks !

**Comment by falloutdurham** [comment]
Added!

**Comment by jhagege** [comment]
Great, thanks :)
