### ISSUE TITLE
Chapter_2.ipynb Implicit dimension choice for softmax has been deprecated

### ISSUE THREAD

**Issue by pjgoodall** [falloutdurham/beginners-pytorch-deep-learning#7]
`py:28: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.`

Need dim parameter added to softmax calls.

**Comment by falloutdurham** [comment]
Good point! I'll take a look at updating these when I have some free time 👍

**Comment by mathlusiverse** [comment]
I googled the error message, most suggest using dim=0 or 1. I tried the following and they failed.
      correct = torch.eq(torch.max(F.softmax(output,dim=0), dim=0)[1], targets).view(-1)
      correct = torch.eq(torch.max(F.softmax(output,dim=1), dim=0)[1], targets).view(-1)

I purchased the book, but couldn't find explanation in the book.  Please help.

**Comment by pfrancq** [comment]
When I execute this piece of code mentioned, I have not only the warning but also an error:

RuntimeError: The size of tensor a (2) must match the size of tensor b (64) at non-singleton dimension 0

**Comment by pfrancq** [comment]
> When I execute this piece of code mentioned, I have not only the warning but also an error:
> 
> RuntimeError: The size of tensor a (2) must match the size of tensor b (64) at non-singleton dimension 0

In fact, in the book, it says 'dim=1' while on the github, the code stipulates 'dim=0'. When I replace the later (githuh) by the former (book), the code runs.

**Comment by falloutdurham** [comment]
Yes, sorry about that - as you say, the book was right, but I was fixing typos a few weeks ago and made that one without checking. I also applied SFDoctor's suggestion of a fix while I was there.

**Comment by MarcusFra** [comment]
> > When I execute this piece of code mentioned, I have not only the warning but also an error:
> > RuntimeError: The size of tensor a (2) must match the size of tensor b (64) at non-singleton dimension 0
> 
> In fact, in the book, it says 'dim=1' while on the github, the code stipulates 'dim=0'. When I replace the later (githuh) by the former (book), the code runs.

Hi. Not sure if you meant the dim argument in the softmax() or in the max() method. I think both have to be set to 1. Fell free to take a look at my PR linked.

**Comment by MarcusFra** [comment]
#37 

As it turned out `correct = torch.eq(torch.max(F.softmax(output, dim=1), dim=1)[1], targets)` works and there is no deprecation warning anymore.
I think this issue is solved and can be closed.
